apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api
  labels:
    app: hello-world-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-api
  template:
    metadata:
      labels:
        app: hello-world-api
      annotations:
        lastUpdate: "${now}"
    spec:
      containers:
      - name: hello-world-api
        image: nmatsui/hello-world-api:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-api
  labels:
    app: hello-world-api
spec:
  type: ClusterIP
  selector:
    app: hello-world-api
  ports:
  - port: 3000
    targetPort: hello-world-api
    name: hello-world-api
