apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
  labels:
    app: resterter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restarter
  labels:
    app: resterter
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: restarter
  labels:
    app: resterter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restarter
subjects:
- kind: ServiceAccount
  name: restarter
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restart-hello-world-api
  labels:
    cronjob: restart-hello-world-api
spec:
  concurrencyPolicy: Replace
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restarter
          containers:
          - name: hello-world-api-restarter
            image: k8sregi.azurecr.io/nmatsui/restarter:latest
            imagePullPolicy: Always
            env:
            - name: NAMESPACE
              value: default
            - name: DEPLOYMENT_NAME
              value: hello-world-api
          restartPolicy: OnFailure
